language: haskell

install:
  - cabal install gtk2hs-buildtools
  - cabal install --enable-tests

script:
  - make test-travis || (cat ~/.LambdaHack/config.rules.dump ; tail -n 200 /tmp/stdtest.log ; exit 77)
