install:
  - SET PATH=%APPDATA%\cabal\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.0.2\bin;C:\ProgramData\chocolatey\lib\cabal\tools;%PATH%
  - SET PKG_CONFIG_PATH=C:\msys64\mingw64\lib\pkgconfig
  - SET XDG_DATA_DIRS=C:\msys64\mingw64\share
  - pacman --version
  - appveyor-retry choco install ghc --version 8.0.2 | grep -v '^Extracting '
  - cabal --version
  - appveyor-retry pacman -S -q --noconfirm mingw64/mingw-w64-x86_64-SDL2 mingw64/mingw-w64-x86_64-SDL2_ttf
  - cabal update
  - cabal install happy
  - pwd
  - git clone -q --branch=master https://github.com/Mikolaj/sdl2.git
  - cd sdl2
  - cabal install
  - cd ..
  - git clone -q --branch=master https://github.com/Mikolaj/sdl2-ttf.git
  - cd sdl2-ttf
  - cabal install
  - cd ..

build_script:
  - pwd
  - make build-binary-common
  - cp /c/msys64/mingw64/bin/zlib1.dll artifacts/LambdaHackTheGame
  - cp /c/msys64/mingw64/bin/SDL2.dll artifacts/LambdaHackTheGame
  - cp /c/msys64/mingw64/bin/SDL2_ttf.dll artifacts/LambdaHackTheGame
  - cp artifacts/LambdaHackTheGameInstall/msys64/bin/LambdaHack.exe artifacts/LambdaHackTheGame
  - 7z a -ssc -sfx artifacts\LambdaHack_windows-x86_64.exe artifacts\LambdaHackTheGame

artifacts:
  - path: artifacts\LambdaHack_windows-x86_64.exe
    name: win64 binaries
