install:
  - SET PATH=%APPDATA%\cabal\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin;C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.0.2\bin;C:\ProgramData\chocolatey\lib\cabal\tools;%PATH%
  - SET PKG_CONFIG_PATH=C:\msys64\mingw64\lib\pkgconfig
  - SET XDG_DATA_DIRS=C:\msys64\mingw64\share
  - pacman --version
  - appveyor-retry choco install ghc --version 8.0.2 | grep -v '^Extracting '
  - cabal --version
  - appveyor-retry pacman -S -q --noconfirm mingw64/mingw-w64-x86_64-SDL2 mingw64/mingw-w64-x86_64-SDL2_ttf
  - cabal update
  - cabal install happy
  - pwd
  - git clone -q --branch=master https://github.com/Mikolaj/sdl2.git
  - cd sdl2
  - cabal install
  - cd ..
  - git clone -q --branch=master https://github.com/Mikolaj/sdl2-ttf.git
  - cd sdl2-ttf
  - cabal install
  - cd ..

build_script:
  - pwd
  - make build-binary-common
  - cp /c/msys64/mingw64/bin/zlib1.dll LambdaHackTheGame
  - cp /c/msys64/mingw64/bin/SDL2.dll LambdaHackTheGame
  - cp /c/msys64/mingw64/bin/SDL2_ttf.dll LambdaHackTheGame
  - cp /c/msys64/mingw64/bin/libfreetype-6.dll LambdaHackTheGame
  - cp /c/msys64/mingw64/bin/libgcc_s_seh-1.dll LambdaHackTheGame
  - cp /c/msys64/mingw64/bin/libbz2-1.dll LambdaHackTheGame
  - cp /c/msys64/mingw64/bin/libpng16-16.dll LambdaHackTheGame
  - cp /c/msys64/mingw64/bin/libwinpthread-1.dll LambdaHackTheGame
  - cp LambdaHackTheGameInstall/msys64/bin/LambdaHack.exe LambdaHackTheGame
  - 7z a -ssc -sfx LambdaHack_windows-x86_64.exe LambdaHackTheGame
  - make test

artifacts:
  - path: LambdaHack_windows-x86_64.exe
    name: win64 binaries
